Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-11, with the labels that each got.

#488 updated SQL in institutions builder for SCO area code and phone number information
  app/models/institution_builder.rb
Labels: BAH, bug

#481 Address RSpec/ExampleLength rubocop errors in GIDS
  .rubocop.yml
  .rubocop_todo.yml
  spec/controllers/dashboards_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_spec.rb
  spec/models/institution_tree_spec.rb
  spec/models/shared_examples/shared_examples_for_archivable.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/upload_spec.rb
  spec/request/institutions_request_spec.rb
  spec/request/zipcode_rates_request_spec.rb
  spec/validators/edu_program_validator_spec.rb
  spec/validators/program_validator_spec.rb
Labels: BAH, BAH-IR-needed

#491 Fix unit tests
  spec/models/institution_builder_spec.rb
Labels: BAH

#489 Remove null constraints from veterans programs columns
  db/migrate/20191104095800_update_edu_programs.rb
  db/schema.rb
Labels: BAH

#487 Bah 19871
  app/serializers/institution_program_profile_serializer.rb
  spec/serializers/institution_program_profile_serializer_spec.rb
Labels: BAH

#490 update serializer to include vet programs data
  app/serializers/institution_program_profile_serializer.rb
  spec/serializers/institution_program_profile_serializer_spec.rb
Labels: BAH, BAH-IR-needed

#486 Program search update
  app/controllers/v0/institution_programs_controller.rb
  app/models/institution_program.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/factories/institution_programs.rb
  spec/models/institution_program_spec.rb
Labels: BAH

#494 Update brakeman to 4.7.1
  Gemfile.lock
Labels: BAH

#497 CT 116: Update EDU Program File Processing and Data Display #19956
  db/migrate/20191112183932_allow_nulls_edu_programs.rb
  db/schema.rb
Labels: BAH

#493 CT 116: Update EDU Program File Processing and Data Display #19956
  app/models/edu_program.rb
  app/models/institution_builder.rb
  app/validators/edu_program_validator.rb
  sample_csvs/edu_program.csv
  spec/validators/edu_program_validator_spec.rb
Labels: BAH
