Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-08, with the labels that each got.

#404 DB migration for: Version Export and Generation Updates
  db/migrate/20190718121700_add_completion_date_to_version.rb
  db/schema.rb
Labels: BAH, database-migration

#406 Add font-awesome-rails
  Gemfile
  Gemfile.lock
Labels: BAH, package-change

#408 updated calculator constants csv
  sample_csvs/calculator_constant.csv
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#392 Version Export and Generation Updates
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/controllers/dashboards_controller.rb
  app/models/institution_builder.rb
  app/models/version.rb
  app/views/dashboards/_version.html.erb
  app/views/dashboards/index.html.erb
  config/routes.rb
  lib/csv_helper/exporter.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/version_spec.rb
Labels: BAH, bah-sprint-26, bah-sprint-27

#403 DB - CT 111: Update CT to properly utilize STEM indicator column #19417
  db/migrate/20190802172014_add_column_stem_indicator_to_institution.rb
  db/schema.rb
Labels: BAH, database-migration

#402 DB - Update GIDS Database to archive historical versions of the software #19015
  db/migrate/20190806012000_create_institutions_archive.rb
  db/schema.rb
Labels: BAH, database-migration

#383 Update GIDS Database to archive historical versions of the software #19015
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/dashboards_controller.rb
  app/models/gibct_site_mapper.rb
  app/models/institutions_archive.rb
  app/models/version.rb
  config/initializers/config.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  lib/csv_helper/exporter.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/institutions_archive_spec.rb
  spec/support/devise.rb
Labels: BAH, bah-sprint-25, bah-sprint-26, bah-sprint-27

#410 Remove ES6 JS
  app/assets/javascripts/application.js
Labels: BAH, BAH-IR-needed

#407 DB migration for: Add support for child facilities
  db/migrate/20190808112100_add_campus_type_columns.rb
  db/migrate/20190808112200_add_parent_facility_code_index_to_intititutions.rb
  db/schema.rb
Labels: BAH, database-migration

#412 Update nokogiri
  Gemfile.lock
Labels: BAH

#411 Institution facility map
  app/models/institution.rb
  app/models/institution_tree.rb
  app/serializers/institution_profile_serializer.rb
  spec/models/institution_tree_spec.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#414 Remove extension institutions from search results
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/weams.rb
  spec/models/institution_builder_spec.rb
Labels: BAH

#413 Added programs.csv to GIDS
  app/models/institution_builder.rb
  app/models/program.rb
  config/csv_file_defaults.yml
  db/migrate/20190809104513_create_program.rb
  db/schema.rb
  db/seeds/02_data.rb
  sample_csvs/program.csv
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/program.rb
  spec/fixtures/program.csv
  spec/fixtures/program_invalid.csv
  spec/fixtures/program_missing_column.csv
  spec/models/program_spec.rb
  spec/models/version_spec.rb
Labels: BAH

#415 19451: Add ability to upload SCO file to GIDS
  app/models/institution_builder.rb
  app/models/school_certifying_official.rb
  config/csv_file_defaults.yml
  db/migrate/20190819111223_create_school_certifying_official.rb
  db/schema.rb
  db/seeds/02_data.rb
  sample_csvs/school_certifying_official.csv
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/school_certifying_official.rb
  spec/fixtures/school_certifying_official.csv
  spec/fixtures/school_certifying_official_invalid.csv
  spec/fixtures/school_certifying_official_missing_column.csv
  spec/models/school_certifying_official_spec.rb
  spec/models/version_spec.rb
Labels: BAH

#420 Cleanup of vet tec institution 'approved' logic
  app/models/weam.rb
  spec/factories/weams.rb
  spec/models/institution_builder_spec.rb
  spec/models/weam_spec.rb
Labels: BAH

#421 CT 116: Make SCO & Program files not required to generate a new GIDS preview version #19526
  .gitignore
  app/controllers/dashboards_controller.rb
  app/helpers/dashboards_helper.rb
  app/models/institution_builder.rb
  app/models/storage.rb
  app/models/upload.rb
  app/models/version.rb
  app/views/dashboards/_latest_upload.html.erb
  app/views/storages/_csv_type_select.html.erb
  app/views/uploads/_csv_type_select.html.erb
  config/initializers/csv_types.rb
  spec/config/initializers/csv_types_spec.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/uploads.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/models/version_spec.rb
Labels: BAH
