Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-09, with the labels that each got.

#429 Develop process to do a production dependency build for testing #19575
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
Labels: BAH, BAH-QA-needed

#433 Facility map duplicate institutions fix
  app/models/institution_tree.rb
  spec/models/institution_tree_spec.rb
Labels: BAH

#431 Update Ruby to vets-api's Ruby version #19606
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  app/models/complaint.rb
  app/models/errors/warning.rb
  app/models/upload.rb
  lib/csv_helper/loader.rb
  spec/models/institution_tree_spec.rb
Labels: BAH

#436 19534: CT 116: Add SCO information to VET TEC Profile page
  Gemfile.lock
  app/models/institution.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/school_certifying_official_serializer.rb
  sample_csvs/school_certifying_official.csv
  spec/support/api/schemas/institution_profile.json
Labels: BAH, bah-ct-116

#435 Add programs to VET TEC Profile Page bah-19614
  app/models/institution.rb
  app/models/program.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/program_serializer.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH, bah-ct-116

#440 Create zipcode_rate_archives table
  db/migrate/20190916105800_create_zipcode_rates_archives.rb
  db/schema.rb
Labels: BAH

#439 Add Zipcode Rate Archiving
  app/controllers/dashboards_controller.rb
  app/models/archiver.rb
  app/models/institutions_archive.rb
  app/models/zipcode_rates_archive.rb
  config/settings.yml
  spec/controllers/dashboards_controller_spec.rb
  spec/models/archiver_spec.rb
  spec/models/institutions_archive_spec.rb
  spec/models/shared_examples/shared_examples_for_archivable.rb
  spec/models/zipcode_rates_archive_spec.rb
Labels: BAH, BAH-QA-needed

#442 Institution programs migrations
  db/migrate/20190916163500_create_institution_programs.rb
  db/migrate/20190916164300_create_institution_programs_archives.rb
  db/schema.rb
Labels: BAH

#443 CT 116: Allow for new preview version to be generated without uploading a file #19667
  app/assets/javascripts/application.js
  app/assets/javascripts/preview.js
  app/assets/stylesheets/application.css
  app/controllers/dashboards_controller.rb
  app/models/upload.rb
  app/models/version.rb
  app/views/dashboards/_latest_upload_dialog.html.erb
  app/views/dashboards/index.html.erb
  config/initializers/csv_types.rb
  spec/config/initializers/csv_types_spec.rb
  spec/models/upload_spec.rb
  spec/models/version_spec.rb
  spec/request/dashboard_request_spec.rb
Labels: BAH

#441 Add institution programs
  app/models/archiver.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/institution_program.rb
  app/models/institution_programs_archive.rb
  app/models/program.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_program_serializer.rb
  spec/factories/institution_programs.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_programs_archive_spec.rb
  spec/models/institution_spec.rb
  spec/models/institution_tree_spec.rb
  spec/serializers/institution_program_serializer_spec.rb
Labels: BAH

#444 Edu Programs Migrations
  db/migrate/20190923162900_create_edu_programs.rb
  db/migrate/20190923162901_add_edu_programs_columns_to_institution_programs.rb
  db/migrate/20190923162902_add_edu_programs_columns_to_institution_programs_archives.rb
  db/schema.rb
Labels: BAH

#448 Staging CT 116: Able to close out of generating new preview version by pressing ESC key #19732
  app/assets/javascripts/preview.js
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
Labels: BAH

#449 GIBCT Dashboard missing styling #19742
  Gemfile
  Gemfile.lock
  app/assets/javascripts/preview.js
  app/models/institution_builder.rb
Labels: BAH
