Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-12, with the labels that each got.

#501 For CSV upload, add batch_size to CSV active_record#import
  app/models/gibct_site_mapper.rb
  config/settings.yml
  lib/csv_helper/exporter.rb
  lib/csv_helper/loader.rb
Labels: BAH, BAH-IR-needed

#505 updated nesting limit and fixed specs not in compliance
  .rubocop.yml
  .rubocop_todo.yml
  spec/controllers/dashboards_controller_spec.rb
  spec/models/institution_builder_spec.rb
Labels: BAH, BAH-QA-needed

#509 add csv_row column to programs
  db/migrate/20191204170301_add_csv_row_column_to_programs.rb
  db/schema.rb
Labels: BAH

#508 Disable RSpec/MultipleExpectations cop
  .rubocop.yml
  .rubocop_todo.yml
Labels: BAH, gibct

#507 Improve performance of Program CSV after import validations
  app/controllers/uploads_controller.rb
  app/models/program.rb
  app/validators/base_validator.rb
  app/validators/edu_program_validator.rb
  app/validators/program_validator.rb
  app/validators/shared_messages.rb
  lib/csv_helper/loader.rb
  lib/csv_helper/shared.rb
  spec/factories/program.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/support/factory_generators.rb
  spec/validators/program_validator_spec.rb
Labels: BAH, BAH-QA-needed

#499 Update institution program provider facet
  app/controllers/v0/institution_programs_controller.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
Labels: BAH

#512 Set a default value of search results to 10 per page.
  app/models/institution_program.rb
Labels: BAH

#502 Handle InstitutionProgram duplicate on version generation
  app/models/institution_builder.rb
  spec/models/institution_builder_spec.rb
Labels: BAH, bah-sprint-36

#510 Reuse preview version as Production version on push to production
  app/controllers/dashboards_controller.rb
  app/models/upload.rb
  app/models/version.rb
  db/schema.rb
  db/seeds/02_data.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/gibct_site_mapper_spec.rb
  spec/models/shared_examples/shared_examples_for_archivable.rb
Labels: BAH, BAH-QA-needed, bah-sprint-36

#524 Drop arf_gibills, csv_files, csv_storages, data_csvs, va_crosswalks
  db/migrate/20191216191418_drop_arf_gi_bills.rb
  db/migrate/20191216191639_drop_csv_files.rb
  db/migrate/20191216191725_drop_csv_storages.rb
  db/migrate/20191216192023_drop_data_csvs.rb
  db/migrate/20191216192035_drop_va_crosswalks.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#517 GIDS: Audit and update model validators Database migration
  db/migrate/20191219201253_add_csv_row_column_to_weams.rb
  db/migrate/20191219203831_remove_unique_facility_code_constraint_weams.rb
  db/schema.rb
Labels: BAH
