Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-10, with the labels that each got.

#446 CT 116: Validate Program Data upload to GIDS #19669
  app/controllers/uploads_controller.rb
  app/models/edu_program.rb
  app/models/program.rb
  app/validators/base_validator.rb
  app/validators/edu_program_validator.rb
  app/validators/program_validator.rb
  db/migrate/20190927174523_add_index_programs.rb
  db/schema.rb
  lib/csv_helper/loader.rb
  lib/csv_helper/shared.rb
  sample_csvs/program.csv
  spec/factories/institutions.rb
  spec/validators/edu_program_validator_spec.rb
  spec/validators/program_validator_spec.rb
Labels: BAH, BAH-QA-needed

#454 DB changes for versioned SCO / Archive
  db/migrate/20191002105112_create_versioned_school_certifying_officials.rb
  db/migrate/20191004151515_create_versioned_school_certifying_officials_archives.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#450 Bah versioned sco
  app/models/archiver.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/versioned_school_certifying_official.rb
  app/models/versioned_school_certifying_officials_archive.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/versioned_school_certifying_official_serializer.rb
  spec/factories/versioned_school_certifying_offical.rb
  spec/models/institution_builder_spec.rb
  spec/models/versioned_school_certifying_official_spec.rb
  spec/models/versioned_school_certifying_officials_archive_spec.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#451 Update gibct-data-service Rails to version 5.1.7 #19615
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/accreditation_action.rb
  app/models/accreditation_institute_campus.rb
  app/models/accreditation_record.rb
  app/models/archiver.rb
  app/models/edu_program.rb
  app/models/institution_builder.rb
  app/models/institution_program.rb
  sample_csvs/program.csv
  spec/controllers/storages_controller_spec.rb
  spec/controllers/uploads_controller_spec.rb
Labels: BAH, BAH-QA-needed

#457 Updated Calculator Constants csv in GIDS repo
  sample_csvs/calculator_constant.csv
Labels: BAH

#462 Fix old database migration
  db/migrate/20190607014201_add_column_approved_and_vet_tec_to_institutions.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#422 Use StrongMigrations.target_postgresql_version property #19601
  config/initializers/strong_migrations.rb
Labels: BAH, BAH-QA-needed

#458 CT: Update security rake task to use latest gems and fix issues #19786
  Gemfile
  Gemfile.lock
  app/models/institution.rb
  app/views/dashboards/_version.html.erb
  config/environments/production.rb
Labels: BAH, BAH-QA-needed

#459 Regex cleanup
  app/models/mou.rb
  app/models/weam.rb
  db/seeds/01_users.rb
  spec/factories/mous.rb
  spec/models/institution_builder_spec.rb
  spec/models/mou_spec.rb
Labels: BAH

#465 update rails sass gem to 6.0
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#466 19790: GIDS: Update sentry-raven to same version as vets-api
  Gemfile
  Gemfile.lock
Labels: BAH

#468 Factory bot Update
  Gemfile
  Gemfile.lock
  spec/models/storage_spec.rb
  spec/models/upload_spec.rb
  spec/models/version_spec.rb
Labels: BAH

#469 Update loofah
  Gemfile.lock
Labels: BAH

#455 Institution Program Migration
  db/migrate/20191009142100_add_institution_columns_to_institution_programs.rb
  db/migrate/20191009142101_add_institution_columns_to_institution_programs_archives.rb
  db/migrate/20191015133100_update_institution_programs_indexes.rb
  db/migrate/20191015133300_update_institution_programs_archives_indexes.rb
  db/migrate/20191022125700_update_institution_programs.rb
  db/migrate/20191022125900_update_institution_programs_archives.rb
  db/schema.rb
Labels: BAH, bah-sprint-32

#472 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: BAH

#470 Fixed Leaky Constant Declaration cop
  .rubocop_todo.yml
  spec/config/initializers/csv_types_spec.rb
Labels: BAH

#475 Update strong_migrations property target_postgresql_version to 9.4
  config/initializers/strong_migrations.rb
Labels: BAH

#452 Institution Programs Search
  .rubocop_todo.yml
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/institution_program.rb
  app/models/program.rb
  app/serializers/institution_program_serializer.rb
  config/initializers/search.rb
  config/routes.rb
  db/seeds/02_data.rb
  lib/search/facets.rb
  sample_csvs/edu_program.csv
  sample_csvs/program.csv
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/factories/institution_programs.rb
  spec/factories/institutions.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_program_spec.rb
  spec/models/institution_spec.rb
  spec/serializers/institution_program_serializer_spec.rb
  spec/support/api/schemas/institution_profile.json
  spec/support/api/schemas/institution_programs.json
  spec/support/api/schemas/institutions.json
Labels: BAH, bah-sprint-32

#474 Bah expect in hook cop
  .rubocop_todo.yml
  spec/controllers/dashboards_controller_spec.rb
Labels: BAH, BAH-QA-needed

#482 if CI env variable is present don't seed data
  db/seeds/01_users.rb
  db/seeds/02_data.rb
  spec/models/institution_builder_spec.rb
Labels: BAH, BAH-IR-needed

#484 Bah message spies cop
  .rubocop_todo.yml
  spec/controllers/dashboards_controller_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/shared_examples/shared_examples_for_archivable.rb
Labels: BAH

#480 update specs to satisfy AnyInstance requirement
  .rubocop_todo.yml
  spec/controllers/application_controller_spec.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/gibct_site_mapper_spec.rb
Labels: BAH

#485 Remove sniffybara
  Gemfile
  Gemfile.lock
  spec/controllers/shared_examples/shared_examples_for_authentication.rb
  spec/rails_helper.rb
Labels: BAH

#479 19832 CT: Address RSpec/NamedSubject rubocop errors in GIDS
  .rubocop_todo.yml
  spec/controllers/v0/api_controller_spec.rb
  spec/models/accreditation_action_spec.rb
  spec/models/accreditation_institute_campus_spec.rb
  spec/models/accreditation_record_spec.rb
  spec/models/arf_gi_bill_spec.rb
  spec/models/calculator_constant_spec.rb
  spec/models/complaint_spec.rb
  spec/models/converters/base_converter_spec.rb
  spec/models/converters/boolean_converter_spec.rb
  spec/models/converters/cross_converter_spec.rb
  spec/models/converters/date_converter_spec.rb
  spec/models/converters/display_converter_spec.rb
  spec/models/converters/downcase_converter_spec.rb
  spec/models/converters/facility_code_converter_spec.rb
  spec/models/converters/institution_converter_spec.rb
  spec/models/converters/number_converter_spec.rb
  spec/models/converters/ope6_converter_spec.rb
  spec/models/converters/ope_converter_spec.rb
  spec/models/converters/state_converter_spec.rb
  spec/models/converters/upcase_converter_spec.rb
  spec/models/converters/zip_converter_spec.rb
  spec/models/crosswalk_spec.rb
  spec/models/eight_key_spec.rb
  spec/models/hcm_spec.rb
  spec/models/institution_program_spec.rb
  spec/models/institution_spec.rb
  spec/models/ipeds_cip_code_spec.rb
  spec/models/ipeds_hd_spec.rb
  spec/models/ipeds_ic_ay_spec.rb
  spec/models/ipeds_ic_py_spec.rb
  spec/models/ipeds_ic_spec.rb
  spec/models/mou_spec.rb
  spec/models/outcome_spec.rb
  spec/models/p911_tf_spec.rb
  spec/models/p911_yr_spec.rb
  spec/models/program_spec.rb
  spec/models/school_certifying_official_spec.rb
  spec/models/school_closure_spec.rb
  spec/models/scorecard_spec.rb
  spec/models/sec109_closed_school_spec.rb
  spec/models/sec702_school_spec.rb
  spec/models/sec702_spec.rb
  spec/models/settlement_spec.rb
  spec/models/stem_cip_code_spec.rb
  spec/models/storage_spec.rb
  spec/models/sva_spec.rb
  spec/models/upload_spec.rb
  spec/models/version_spec.rb
  spec/models/versioned_school_certifying_official_spec.rb
  spec/models/vsoc_spec.rb
  spec/models/weam_spec.rb
  spec/models/yellow_ribbon_program_source_spec.rb
Labels: BAH, BAH-QA-needed
