Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2019-07, with the labels that each got.

#376 Generate ZipcodeRates from Weams data
  app/controllers/v0/zipcode_rates_controller.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/zipcode_rate.rb
  app/serializers/institution_profile_serializer.rb
  db/migrate/20190626110700_add_columns_to_zipcode_rates.rb
  db/schema.rb
  db/seeds/02_data.rb
  db/seeds/02_zipcode_rates.rb
  db/seeds/02_zipcode_rates.rb.ignore
  db/seeds/zipcode_rate/mha_rate.txt
  db/seeds/zipcode_rate/zip_mha.txt
  lib/csv_helper/exporter.rb
  spec/factories/weams.rb
  spec/factories/zipcode_rates.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_spec.rb
  spec/request/zipcode_rates_request_spec.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#390 rubocop to 0.53.0
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/auth_controller.rb
  app/controllers/storages_controller.rb
  app/controllers/uploads_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/gibct_site_mapper.rb
  lib/csv_helper/loader.rb
  spec/rails_helper.rb
Labels: BAH

#394 CT 109: Reorder columns in Institution.csv #19162
  app/models/institution.rb
Labels: BAH

#391 Update GIDS to accept new 109 School Closures File 19185
  .gitignore
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/sec109_closed_school.rb
  app/serializers/institution_serializer.rb
  config/csv_file_defaults.yml
  db/migrate/20190711073817_create_sec109_closed_school.rb
  db/migrate/20190711100525_add_column_closure109_to_institutions.rb
  db/schema.rb
  db/seeds/02_data.rb
  sample_csvs/sec109_closed_school.csv
  spec/factories/institutions.rb
  spec/factories/sec109_closed_schools.rb
  spec/fixtures/institution.csv
  spec/fixtures/sec109_closed_school.csv
  spec/fixtures/sec109_closed_school_invalid.csv
  spec/fixtures/sec109_closed_school_missing_column.csv
  spec/models/institution_spec.rb
  spec/models/sec109_closed_school_spec.rb
  spec/models/version_spec.rb
  spec/support/api/schemas/institution_profile.json
  spec/support/api/schemas/institutions.json
Labels: bah-sprint-25

#389 Added Preferred Provider Column to Weams
  app/models/weam.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_serializer.rb
  db/migrate/20190712019179_add_preferred_provider_column_to_institutions.rb
  db/migrate/20190717019179_add_preferred_provider_column_to_weams.rb
  db/schema.rb
  spec/fixtures/weam.csv
  spec/fixtures/weam_extra_column.csv
  spec/fixtures/weam_missing_column.csv
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#396 use safety_assured and change_table for CT 116 Preferred Provider
  db/migrate/20190712019179_add_preferred_provider_column_to_institutions.rb
  db/migrate/20190717019179_add_preferred_provider_column_to_weams.rb
Labels: BAH, BAH-IR-needed

#381 Bah ct111 19025
  app/models/weam.rb
  db/migrate/20190718019025_add_column_stem_indicator_to_weams.rb
  db/schema.rb
  spec/fixtures/weam.csv
  spec/fixtures/weam_extra_column.csv
  spec/fixtures/weam_missing_column.csv
Labels: BAH, bah-sprint-25

#397 CT 116: Sort Search Results to prioritize preferrred providers. #19278
  app/controllers/v0/institutions_controller.rb
  spec/factories/institutions.rb
  spec/factories/sec109_closed_schools.rb
  spec/request/institutions_request_spec.rb
Labels: BAH

#400 CT 116: Add "Preferred Providers" filter on the VET TEC search results #19340
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH
