Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-03, with the labels that each got.

#598 update puma to ~> 3.12.4
  Gemfile
  Gemfile.lock
Labels: BAH

#594 Update/Add rubocop cops
  .rubocop.yml
Labels: BAH

#596 Shared examples for exportable by version
  app/controllers/archives_controller.rb
  app/controllers/dashboards_controller.rb
  lib/csv_helper/exporter.rb
  spec/controllers/archives_controller_spec.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/institution_spec.rb
  spec/models/shared_examples/shared_examples_for_exportable_by_version.rb
Labels: BAH

#595 6265: Correct Duplication of institutions where Non-Unique facility codes exist
  app/models/institution_builder.rb
  spec/models/institution_builder_spec.rb
Labels: BAH

#591 GIDS: Update Data Requirements Display#5752
  app/controllers/uploads_controller.rb
  app/models/upload.rb
  app/views/uploads/_info_box.html.erb
  app/views/uploads/new.html.erb
  app/views/uploads/show.html.erb
  spec/controllers/uploads_controller_spec.rb
  spec/models/upload_spec.rb
Labels: BAH

#599 Update postgres version for strong migrations and docker composes
  config/initializers/strong_migrations.rb
  docker-compose.test.yml
  docker-compose.yml
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#593 Crosswalk Issue Ignore / Force Resolution Migration PR
  db/migrate/20200221090200_create_ignored_crosswalk_issues.rb
  db/schema.rb
Labels: BAH

#592 Crosswalk Issue IPEDS HD match scoring updates
  app/controllers/crosswalk_issues_controller.rb
  app/models/weam.rb
  app/views/crosswalk_issues/show_partial.html.erb
  spec/controllers/crosswalk_issues_controller_spec.rb
  spec/factories/crosswalk_issues.rb
Labels: BAH

#601 Institution CSV Archives blank on export #6355
  app/models/version.rb
  app/views/archives/index.html.erb
  app/views/dashboards/index.html.erb
  spec/controllers/archives_controller_spec.rb
Labels: BAH, BAH-QA-needed

#603 DB migration for parent facility code id index
  db/migrate/20200309101010_add_parent_facility_code_id_index_to_institutions.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#604 GIDS: Reduce the time required for institutions search by ID endpoint#6664
  app/controllers/v0/api_controller.rb
Labels: BAH, BAH-IR-needed

#602 GIDS: Add feature flag / prod flag support #6598
  .rubocop.yml
  README.md
  app/views/layouts/_navbar.html.erb
  config/initializers/common.rb
  config/initializers/figaro.rb
  config/settings.yml
  docker-compose.test.yml
  docker-compose.yml
  spec/config/initializers/common_spec.rb
Labels: BAH

#608 GIDS: Archive Tab is inaccessible in production #6786
  app/views/archives/_version.html.erb
  app/views/dashboards/_version.html.erb
Labels: BAH, BAH-QA-needed

#606 add description column to calculator constants table
  db/migrate/20200310142611_add_description_column_to_calculator_constants.rb
  db/schema.rb
  sample_csvs/calculator_constant.csv
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#600 Create interface to manage CalculatorConstants
  app/assets/javascripts/calculator_constants.js
  app/assets/stylesheets/application.css
  app/controllers/calculator_constants_controller.rb
  app/models/calculator_constant.rb
  app/views/calculator_constants/index.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  sample_csvs/calculator_constant.csv
  spec/controllers/calculator_constants_controller_spec.rb
  spec/factories/calculator_constants.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#610 remove es6 syntax to fix styling issue in staging
  app/assets/javascripts/calculator_constants.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#607 GIDS: Create crosswalk dashboard widget & update GIDS header
  app/assets/stylesheets/application.css
  app/views/dashboards/_crosswalk_issues.html.erb
  app/views/dashboards/index.html.erb
  app/views/layouts/_navbar.html.erb
Labels: BAH

#605 Bah 6666
  app/models/institution_builder.rb
  db/migrate/20200310150006_add_index_to_ipeds_ic_ays.rb
  db/migrate/20200310150007_add_index_to_ipeds_ic_pies.rb
  db/migrate/20200310150008_add_index_to_school_certifying_officials.rb
  db/migrate/20200310150009_add_index_to_sec109_closed_schools.rb
  db/migrate/20200310150010_add_index_to_hcms.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#611 CT: Refactor Caution Flag database migration #6854
  db/migrate/20200316120734_create_caution_flags.rb
  db/schema.rb
Labels: BAH

#613 create sec103 table
  db/migrate/20200316123122_create_sec_103s.rb
  db/migrate/20200316133022_add_sec103_to_institutions.rb
  db/schema.rb
Labels: BAH

#618 GIDS: Research allowing GIDS to handle ES6 or adding a rubocop to keep ES6 out #6855
  app/assets/javascripts/calculator_constants.js
  config/environments/production.rb
Labels: BAH, BAH-QA-needed

#621 Update Rails and Json dependencies
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-QA-needed

#622 Remove sdoc
  Gemfile
  Gemfile.lock
Labels: BAH

#615 Add sec103 data to institutions
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/sec103.rb
  app/serializers/institution_profile_serializer.rb
  app/views/dashboards/_latest_upload.html.erb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  sample_csvs/Sec103.csv
  spec/factories/sec103s.rb
  spec/fixtures/sec103.csv
  spec/fixtures/sec103_invalid.csv
  spec/models/sec103_spec.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#612 CT: Refactor Caution Flag #6854
  app/models/archiver.rb
  app/models/caution_flag.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_serializer.rb
  app/views/storages/_storage.html.erb
  db/seeds/02_data.rb
  spec/models/archiver_spec.rb
  spec/models/institution_builder_spec.rb
  spec/support/api/schemas/institution_profile.json
  spec/support/api/schemas/institutions.json
Labels: BAH

#625 CT: Nulls on caution flag for search results #7114
  app/models/institution_program.rb
  app/serializers/institution_program_serializer.rb
  spec/serializers/institution_program_serializer_spec.rb
Labels: BAH

#624 add 'schoolClosingOn' to institution serializer
  app/models/institution_program.rb
  app/serializers/institution_program_serializer.rb
  app/serializers/institution_serializer.rb
Labels: BAH

#626 CT: Duplicate caution flags on search results #7111
  app/models/institution_builder.rb
Labels: BAH

#627 Add columns to caution_flags
  db/migrate/20200323092001_add_columns_to_caution_flags.rb
  db/schema.rb
Labels: BAH
