Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-04, with the labels that each got.

#631 Update settlement csv with staging file
  sample_csvs/settlement.csv
Labels: BAH

#632 Kelsonic 7443 use name query param and institution name
  app/controllers/v0/yellow_ribbon_programs_controller.rb
  app/models/yellow_ribbon_program.rb
  app/serializers/yellow_ribbon_program_serializer.rb
  sample_csvs/yellow_ribbon_program_source.csv
  spec/controllers/v0/yellow_ribbon_programs_controller_spec.rb
  spec/factories/yellow_ribbon_program.rb
  spec/serializers/yellow_ribbon_program_serializer_spec.rb
  spec/support/api/schemas/yellow_ribbon_program.json
Labels: gibct

#628 Add new caution flag fields
  app/serializers/caution_flag_serializer.rb
  app/serializers/institution_profile_serializer.rb
  spec/factories/caution_flags.rb
  spec/serializers/caution_flag_serializer_spec.rb
Labels: BAH

#634 CF: Mapping Caution Flag Content: Database changes
  db/migrate/20200327133637_create_rules.rb
  db/migrate/20200327142848_create_caution_flag_rules.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#633 CF: Mapping Caution Flag Content: Add Gem
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-IR-needed

#636 caution flag filter migration
  db/migrate/20200401125410_add_count_of_caution_flags_column_to_institutions.rb
  db/migrate/20200402101010_add_count_of_caution_flags_column_to_institutions_archives.rb
  db/schema.rb
Labels: BAH

#635 Caution flag filters backend
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/caution_flag.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_serializer.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
  spec/support/api/schemas/institution_profile.json
  spec/support/api/schemas/institutions.json
Labels: BAH

#630 CF: Mapping Caution Flag Content #7151
  .rubocop.yml
  app/models/caution_flag.rb
  app/models/caution_flag_rule.rb
  app/models/institution_builder.rb
  app/models/rule.rb
  db/seeds/02_data.rb
  db/seeds/03_rules.rb
  db/seeds/99_build.rb
  spec/factories/caution_flag_rules.rb
  spec/factories/caution_flags.rb
  spec/factories/rules.rb
  spec/models/caution_flag_rule_spec.rb
  spec/models/caution_flag_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/rule_spec.rb
Labels: BAH

#637 CF: Exclude institutions with warnings filter not excluding cautionary warnings#7747
  app/models/institution_builder.rb
  spec/models/institution_builder_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#640 Standardize caution flag institution URLS
  app/models/caution_flag.rb
  spec/factories/caution_flag_rules.rb
  spec/factories/caution_flags.rb
  spec/factories/rules.rb
  spec/models/caution_flag_spec.rb
Labels: BAH

#642 CF: Exclude institutions with warnings filter not excluding cautionary warnings #7747
  app/models/institution_builder.rb
Labels: BAH

#641 Add section_103_message column to institutions
  db/migrate/20200414145010_add_section_103_message_column_to_institutions.rb
  db/migrate/20200415150200_add_section_103_message_column_to_institutions_archives.rb
  db/schema.rb
Labels: BAH

#645 CF: Update mapping logic when settlement description is not found in caution flag content #7578
  db/migrate/20200420194305_set_defaults_caution_flags.rb
  db/schema.rb
Labels: BAH

#644 CF: Update caution flag content based on DEPO staging review feedback. #8082
  app/models/caution_flag.rb
  db/seeds/03_rules.rb
  lib/tasks/seed_rules.rake
  lib/tasks/update_zipcode_rates.rake
  sample_csvs/settlement.csv
  spec/factories/caution_flags.rb
  spec/models/caution_flag_spec.rb
Labels: BAH

#649 CF: Production duplicates of caution flag#8413
  app/models/caution_flag.rb
  app/models/institution.rb
  app/serializers/caution_flag_serializer.rb
  spec/models/caution_flag_spec.rb
Labels: BAH, BAH-QA-needed

#648 Add closed schools to search results caution flag filter
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed
