Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-08, with the labels that each got.

#692 11306 Update Search Results page with new filters
  .rubocop.yml
  app/controllers/v0/institutions_controller.rb
Labels: BAH

#697 Update institution search API
  app/models/institution.rb
Labels: BAH, BAH-QA-needed

#698 CF: Include new VA Caution Flags CSV in version generation Pre Database changes #11354
  db/migrate/20200805191336_add_flag_date_to_caution_flags.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#702 Exclude removed CSV types from displaying in Latest Uploads
  app/controllers/dashboards_controller.rb
  app/models/storage.rb
  app/models/upload.rb
  app/views/storages/_csv_type_select.html.erb
  app/views/uploads/_csv_type_select.html.erb
  config/initializers/csv_types.rb
  spec/config/initializers/csv_types_spec.rb
  spec/controllers/dashboards_controller_spec.rb
Labels: BAH, BAH-QA-needed

#704 Institution Search API change city criteria to UPPER LIKE comparison
  app/models/institution.rb
Labels: BAH

#705 Add post 911 stats table
  db/migrate/20200806074500_create_post_911_stats.rb
  db/schema.rb
Labels: BAH

#701 Post911 cleanup
  db/migrate/20200806141100_drop_p911_tfs.rb
  db/migrate/20200806141200_drop_p911_yrs.rb
  db/schema.rb
Labels: BAH

#694 CF: Include new VA Caution Flags CSV in version generation #11354
  .rubocop.yml
  app/models/caution_flag.rb
  app/models/caution_flag_rule.rb
  app/models/institution_builder.rb
  app/models/school_closure.rb
  app/models/sec702_school.rb
  app/models/settlement.rb
  app/utilities/caution_flag_templates/accreditation_caution_flag.rb
  app/utilities/caution_flag_templates/caution_flag_template.rb
  app/utilities/caution_flag_templates/hcm_caution_flag.rb
  app/utilities/caution_flag_templates/mou_caution_flag.rb
  app/utilities/caution_flag_templates/sec702_caution_flag.rb
  config/application.rb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  db/seeds/03_rules.rb
  lib/tasks/seed_rules.rake
  sample_csvs/school_closure.csv
  sample_csvs/sec702_school.csv
  sample_csvs/settlement.csv
  spec/config/initializers/csv_types_spec.rb
  spec/factories/caution_flag_rules.rb
  spec/factories/caution_flags.rb
  spec/factories/rules.rb
  spec/factories/school_closure.rb
  spec/factories/sec702_schools.rb
  spec/factories/settlements.rb
  spec/factories/va_caution_flags.rb
  spec/factories/weams.rb
  spec/fixtures/school_closure.csv
  spec/fixtures/school_closure_invalid.csv
  spec/fixtures/school_closure_missing_column.csv
  spec/fixtures/sec702_school.csv
  spec/fixtures/sec702_school_invalid.csv
  spec/fixtures/sec702_school_missing_column.csv
  spec/fixtures/settlement.csv
  spec/fixtures/settlement_invalid.csv
  spec/fixtures/settlement_missing_column.csv
  spec/models/caution_flag_rule_spec.rb
  spec/models/caution_flag_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/rule_spec.rb
  spec/models/school_closure_spec.rb
  spec/models/sec702_school_spec.rb
  spec/models/settlement_spec.rb
  spec/utilities/caution_flags/caution_flag_template_spec.rb
Labels: BAH, BAH-QA-needed

#706 Update Seeding process for Scorecard to fetch from API
  README.md
  db/seeds/02_data.rb
  lib/seed_utils.rb
Labels: BAH, BAH-IR-needed

#707 Drop Settlement, Caution Flag Rule, Rule, Sec702 School, School Closure tables
  db/migrate/20200814183045_drop_settlement.rb
  db/migrate/20200814183406_drop_sec702_school.rb
  db/migrate/20200814183445_drop_school_closure.rb
  db/migrate/20200814183702_drop_caution_flag_rules.rb
  db/migrate/20200814183825_drop_rule.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#708 Revert Seeding Scorecard by API
  README.md
  db/seeds/02_data.rb
  lib/seed_utils.rb
  sample_csvs/scorecard.csv
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#696 10983: Add Scorecard alias data element to version data (db specfic pr)
  db/migrate/20200804165748_add_alias_to_scorecard.rb
  db/schema.rb
Labels: BAH

#711 Update Scorecard Sample CSV with alias column data
  sample_csvs/scorecard.csv
Labels: BAH

#710 CT Site Search: Update Free Text Search of City Data Behavior #12810
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
  spec/models/institution_spec.rb
Labels: BAH

#712 CT Institution Search
  app/models/institution.rb
Labels: BAH, BAH-QA-needed
