Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-06, with the labels that each got.

#660 CF: Remove Section 103 prod flag for GIDS #9629
  app/models/institution_builder.rb
  app/views/dashboards/_latest_upload.html.erb
  config/initializers/csv_types.rb
Labels: BAH

#669 9851: Update caution flag plain language mappings
  db/seeds/03_rules.rb
Labels: BAH, BAH-QA-needed

#672 Update README.md
  README.md
Labels: BAH

#673 CF: Update FTC settlement caution flag plain language mappings #10474
  db/seeds/03_rules.rb
Labels: BAH, BAH-QA-needed

#674 CF: Update FTC settlement caution flag plain language mappings #10474
  db/seeds/03_rules.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#675 add poo status to institutions and institutions_archives tables
  db/migrate/20200626165535_add_poo_status_to_institutions.rb
  db/schema.rb
Labels: BAH

#676 GIDS: Add 'POO Status' data to version export #10358
  app/models/institution.rb
  app/models/weam.rb
Labels: BAH
