Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-10, with the labels that each got.

#735 Institution ratings
  app/models/archiver.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/institution_category_rating.rb
  app/models/institution_category_ratings_archive.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_serializer.rb
  db/migrate/20200924180331_create_institution_category_ratings.rb
  db/migrate/20200924180714_create_institution_category_ratings_archives.rb
  db/migrate/20200924180839_add_rating_fields_to_institutions.rb
  db/migrate/20200930081100_add_rating_fields_to_institutions_archives.rb
  db/schema.rb
  db/seeds/02_data.rb
  sample_csvs/school_rating.csv
  spec/factories/institution_category_ratings.rb
  spec/factories/school_ratings.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_category_ratings_archive_spec.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#738 Refactor code related to File Uploads
  app/controllers/uploads_controller.rb
  app/models/accreditation_action.rb
  app/models/accreditation_record.rb
  app/models/arf_gi_bill.rb
  app/models/calculator_constant.rb
  app/models/complaint.rb
  app/models/crosswalk.rb
  app/models/edu_program.rb
  app/models/eight_key.rb
  app/models/hcm.rb
  app/models/importable_record.rb
  app/models/institution.rb
  app/models/ipeds_cip_code.rb
  app/models/ipeds_hd.rb
  app/models/ipeds_ic.rb
  app/models/ipeds_ic_ay.rb
  app/models/ipeds_ic_py.rb
  app/models/mou.rb
  app/models/outcome.rb
  app/models/post911_stat.rb
  app/models/program.rb
  app/models/school_certifying_official.rb
  app/models/school_rating.rb
  app/models/scorecard.rb
  app/models/sec103.rb
  app/models/sec109_closed_school.rb
  app/models/sec702.rb
  app/models/stem_cip_code.rb
  app/models/sva.rb
  app/models/va_caution_flag.rb
  app/models/vsoc.rb
  app/models/weam.rb
  app/models/yellow_ribbon_program_source.rb
  lib/csv_helper/loader.rb
  lib/csv_helper/shared.rb
  lib/seed_utils.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/scorecard_spec.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/shared_examples/shared_examples_for_loadable.rb
Labels: BAH, BAH-QA-needed

#736 Institution rating calculation improvements
  app/models/institution_builder.rb
  spec/models/institution_builder_spec.rb
Labels: BAH

#740 Add roo gem for excel file uploads
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#742 For uploads reorder warnings messages and populate warnings even if error occurs
  app/controllers/uploads_controller.rb
  app/views/uploads/_upload_messages.html.erb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#741 Refactor csv file defaults
  app/models/accreditation_institute_campus.rb
  app/models/rule.rb
  app/models/upload.rb
  config/csv_file_defaults.yml
  lib/common/shared.rb
  lib/csv_helper/exporter.rb
  lib/csv_helper/shared.rb
  lib/seed_utils.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/importable_record_spec.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/shared_examples/shared_examples_for_exportable_by_version.rb
  spec/models/shared_examples/shared_examples_for_loadable.rb
  spec/rails_helper.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#743 Enable new search functionality to support removal of gibct_search_enhancements feature flag
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_program.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
  spec/models/institution_spec.rb
Labels: BAH

#745 ImportableRecord updates
  app/controllers/uploads_controller.rb
  app/models/arf_gi_bill.rb
  app/models/complaint.rb
  app/models/crosswalk.rb
  app/models/edu_program.rb
  app/models/eight_key.rb
  app/models/hcm.rb
  app/models/institution.rb
  app/models/mou.rb
  app/models/post911_stat.rb
  app/models/program.rb
  app/models/school_certifying_official.rb
  app/models/school_rating.rb
  app/models/sec103.rb
  app/models/sec702.rb
  app/models/stem_cip_code.rb
  app/models/sva.rb
  app/models/upload.rb
  app/models/va_caution_flag.rb
  app/models/weam.rb
  app/models/yellow_ribbon_program_source.rb
  app/views/uploads/_info_box.html.erb
  lib/common/shared.rb
  lib/csv_helper/exporter.rb
  lib/csv_helper/loader.rb
  spec/models/importable_record_spec.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/shared_examples/shared_examples_for_exportable_by_version.rb
Labels: BAH

#737 GIDS: Add the ability to upload a single tab excel file #14735
  .rubocop.yml
  app/controllers/uploads_controller.rb
  app/models/importable_record.rb
  app/models/upload.rb
  app/views/uploads/_form.html.erb
  config/csv_file_defaults.yml
  config/initializers/roo_helper.rb
  config/settings.yml
  lib/common/loader.rb
  lib/common/shared.rb
  lib/csv_helper/loader.rb
  lib/roo_helper/loader.rb
  lib/roo_helper/shared.rb
  lib/seed_utils.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/uploads.rb
  spec/fixtures/invalid_col_sep.csv
  spec/lib/common/shared_spec.rb
  spec/lib/roo_helper/loader_spec.rb
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/shared_examples/shared_examples_for_loadable.rb
  spec/models/upload_spec.rb
Labels: BAH, BAH-QA-needed

#750 Moved PROGRAM_TYPES enum to program model
  app/models/institution_program.rb
  app/models/program.rb
Labels: BAH

#753 Refactor CSV type to be Upload types
  .rubocop.yml
  app/controllers/dashboards_controller.rb
  app/helpers/dashboards_helper.rb
  app/models/storage.rb
  app/models/upload.rb
  app/views/dashboards/_latest_upload.html.erb
  app/views/storages/_csv_type_select.html.erb
  app/views/uploads/_csv_type_select.html.erb
  config/initializers/csv_types.rb
  config/initializers/upload_types.rb
  spec/config/initializers/csv_types_spec.rb
  spec/config/initializers/upload_types_spec.rb
Labels: BAH

#756 Remove return from upload_types
  config/initializers/upload_types.rb
Labels: BAH

#758 Group uploads: add hidden field for param when checkbox is not displayed
  app/views/groups/_form.html.erb
Labels: BAH
