Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-02, with the labels that each got.

#555 GIDS: Auto-detect file delimiter #5212
  .rubocop.yml
  app/controllers/uploads_controller.rb
  app/models/upload.rb
  app/views/uploads/_form.html.erb
  config/settings.yml
  spec/controllers/uploads_controller_spec.rb
  spec/fixtures/weam_caret_col_sep.csv
  spec/models/upload_spec.rb
Labels: BAH

#557 Add pg_trgm Postgres extension and Institution indexes
  db/migrate/20200203121800_add_pg_trgm_extension.rb
  db/migrate/20200203122100_remove_institutions_address_indexes.rb
  db/migrate/20200203122200_add_trigram_indexes_to_institutions.rb
  db/migrate/20200203122400_add_country_index_to_institutions.rb
  db/schema.rb
Labels: BAH

#553 Improve institutions query performance
  app/controllers/v0/institution_programs_controller.rb
  app/models/institution.rb
  app/models/institution_program.rb
  spec/models/institution_spec.rb
Labels: BAH

#548 GIDS: Allow for download of historically published versions #4615
  app/assets/stylesheets/application.css
  app/controllers/archives_controller.rb
  app/models/version.rb
  app/views/archives/_version.html.erb
  app/views/archives/index.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  lib/csv_helper/exporter.rb
  spec/controllers/archives_controller_spec.rb
  spec/models/version_spec.rb
Labels: BAH, BAH-QA-needed

#549 Crosswalk Update - Partial Weams Match
  app/assets/javascripts/crosswalk_issues/show.js
  app/assets/stylesheets/application.css
  app/controllers/crosswalk_issues_controller.rb
  app/controllers/crosswalks_controller.rb
  app/models/crosswalk_issue.rb
  app/views/crosswalk_issues/_orphan_issues.html.erb
  app/views/crosswalk_issues/_partial_issues.html.erb
  app/views/crosswalk_issues/orphans.html.erb
  app/views/crosswalk_issues/partials.html.erb
  app/views/crosswalk_issues/show_partial.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  spec/controllers/crosswalk_issues_controller_spec.rb
  spec/controllers/crosswalks_controller_spec.rb
  spec/factories/crosswalk_issues.rb
  spec/models/crosswalk_issue_spec.rb
Labels: BAH

#564 Remove VET TEC institutions from Institutions search
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
  spec/request/institutions_request_spec.rb
Labels: BAH

#568 Update crosswalk-issues/partials form path
  app/views/crosswalk_issues/show_partial.html.erb
  config/routes.rb
Labels: BAH

#566 Deploy information and general updates to README.md
  README.md
Labels: BAH

#570 Exclude VET TEC institutions from search and autocomplete only
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH, BAH-QA-needed

#560 GIDS: Order crosswalk issues by number of GI bill students. #5342
  app/controllers/crosswalk_issues_controller.rb
  app/models/arf_gi_bill.rb
  app/models/weam.rb
  app/views/crosswalk_issues/_partial_issues.html.erb
  app/views/crosswalk_issues/partials.html.erb
  spec/controllers/crosswalk_issues_controller_spec.rb
  spec/factories/crosswalk_issues.rb
  spec/factories/weams.rb
Labels: BAH, BAH-QA-needed

#567 fuzzy searching for partial matches of ipeds_hd data for crosswalk_issues
  app/controllers/crosswalk_issues_controller.rb
  app/models/ipeds_hd.rb
  app/models/weam.rb
  app/views/crosswalk_issues/_partial_issues.html.erb
  app/views/crosswalk_issues/find_matches.html.erb
  config/routes.rb
  spec/controllers/crosswalk_issues_controller_spec.rb
  spec/factories/crosswalk_issues.rb
Labels: BAH, BAH-IR-needed

#571 Remove institution_archives constraint from db
  db/migrate/20200210150004_remove_institutions_archives_version_constraint.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#573 Add the matching score to the matching Ipeds_HD table
  app/controllers/crosswalk_issues_controller.rb
  app/views/crosswalk_issues/find_matches.html.erb
  spec/controllers/crosswalk_issues_controller_spec.rb
Labels: BAH

#577 Remove explict post that breaks form submission
  app/views/crosswalk_issues/find_matches.html.erb
Labels: BAH

#575 Bah uploadtransaction 5361
  lib/csv_helper/loader.rb
  spec/models/shared_examples/shared_examples_for_loadable.rb
Labels: BAH

#576 Add institution_id to versioned school certifying officials
  app/models/school_certifying_official.rb
  db/migrate/20200212204337_add_institution_id_to_versioned_school_certifying_officials.rb
  db/migrate/20200212205137_add_institution_id_to_versioned_school_certifying_officials_archives.rb
  db/migrate/20200212206022_drop_school_certifying_officials_archives.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#550 Bah 4038 Refactor archiver to handle parent/child relationships
  .rubocop.yml
  app/controllers/v0/api_controller.rb
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/controllers/v0/zipcode_rates_controller.rb
  app/models/archiver.rb
  app/models/complaint.rb
  app/models/gibct_site_mapper.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/institution_program.rb
  app/models/institution_tree.rb
  app/models/school_certifying_official.rb
  app/models/version.rb
  app/models/versioned_school_certifying_official.rb
  app/models/zipcode_rate.rb
  app/serializers/institution_profile_serializer.rb
  db/migrate/20200107150001_create_school_certifying_officials_archives.rb
  db/migrate/20200107150004_remove_institutions_version_constraint.rb
  lib/csv_helper/exporter.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institution_programs.rb
  spec/factories/institutions.rb
  spec/models/archiver_spec.rb
  spec/models/complaint_spec.rb
  spec/models/gibct_site_mapper_spec.rb
  spec/models/institution_builder_spec.rb
  spec/models/institution_program_spec.rb
  spec/models/institution_spec.rb
  spec/models/institution_tree_spec.rb
  spec/models/shared_examples/shared_examples_for_archivable.rb
  spec/models/version_spec.rb
  spec/models/versioned_school_certifying_officials_archive_spec.rb
  spec/request/institutions_request_spec.rb
  spec/request/zipcode_rates_request_spec.rb
  spec/serializers/institution_program_profile_serializer_spec.rb
  spec/serializers/institution_program_serializer_spec.rb
Labels: BAH

#583 Pre ruby 2.5.7 Update rubocop
  Gemfile.lock
  Rakefile
  app/controllers/uploads_controller.rb
Labels: BAH, BAH-IR-needed

#574 Institution and InstitutionProgram Autocomplete Filters
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution_program.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institution_programs.rb
  spec/factories/institutions.rb
  spec/models/institution_program_spec.rb
Labels: BAH

#589 Flush stdout to display error output in jenkins
  Makefile
  lib/tasks/ci.rake
  lib/tasks/support/shell_command.rb
Labels: BAH

#581 4043 School Certifying Officials cleanup
  app/models/school_certifying_official.rb
  db/migrate/20200220184720_remove_institution_id_from_school_certifying_officials.rb
  db/schema.rb
Labels: BAH

#582 Update sitemap_generator
  Gemfile
  Gemfile.lock
Labels: BAH

#580 Combine Partial Match Crosswalk Issue edit pages
  app/assets/stylesheets/application.css
  app/controllers/crosswalk_issues_controller.rb
  app/views/crosswalk_issues/_partial_issues.html.erb
  app/views/crosswalk_issues/find_matches.html.erb
  app/views/crosswalk_issues/show_partial.html.erb
  config/routes.rb
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  spec/controllers/crosswalk_issues_controller_spec.rb
  spec/factories/crosswalk_issues.rb
Labels: BAH

#590 GIDS: Institution CSV is blank on export #6201
  lib/csv_helper/exporter.rb
  spec/factories/institutions.rb
  spec/models/institution_spec.rb
Labels: BAH

#585 Update File Upload Status Alerts to be more Readable
  app/controllers/uploads_controller.rb
  app/views/layouts/application.html.erb
  app/views/uploads/_form.html.erb
  app/views/uploads/_upload_messages.html.erb
  app/views/uploads/new.html.erb
  app/views/uploads/show.html.erb
  spec/controllers/uploads_controller_spec.rb
Labels: BAH
