Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-01, with the labels that each got.

#519 Bah 4063 Database Specific Changes
  db/migrate/20191211111000_add_version_id_column_to_zipcode_rates.rb
  db/migrate/20191211111001_add_version_id_column_to_zipcode_rates_archives.rb
  db/migrate/20191211111002_add_version_id_column_to_institutions.rb
  db/migrate/20191211111003_add_version_id_column_to_institutions_archives.rb
  db/schema.rb
Labels: BAH

#535 Add Faraday gems to use for API calls within GIDS
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-QA-needed, bah-comparisontool

#537 Bah schema.rb fix
  db/migrate/20191211111001_add_version_id_column_to_zipcode_rates_archives.rb
  db/migrate/20191211111003_add_version_id_column_to_institutions_archives.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#522 Crosswalk Issues DB Migration
  db/migrate/20191219210000_add_ope_and_cross_indexes_to_weams.rb
  db/migrate/20191219210001_add_institution_and_ope_indexes_to_ipeds_hds.rb
  db/migrate/20191219210002_create_crosswalk_issues.rb
  db/schema.rb
Labels: BAH

#529 4063: Setup parent/child version relationships for institutions and zip code rates.
  app/models/institution_builder.rb
Labels: BAH

#527 4044: Add parent institution relationship to SCO & Program data
  app/models/institution.rb
  app/models/school_certifying_official.rb
  app/serializers/institution_profile_serializer.rb
Labels: BAH

#523 Crosswalk issues list
  app/assets/stylesheets/application.css
  app/controllers/crosswalks_controller.rb
  app/controllers/uploads_controller.rb
  app/models/crosswalk.rb
  app/models/crosswalk_issue.rb
  app/models/ipeds_hd.rb
  app/models/weam.rb
  app/views/crosswalks/_issues.html.erb
  app/views/crosswalks/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/uploads/show.html.erb
  config/routes.rb
  db/seeds/02_data.rb
  spec/controllers/crosswalks_controller_spec.rb
  spec/factories/crosswalk_issues.rb
  spec/factories/crosswalks.rb
  spec/factories/ipeds_hds.rb
  spec/factories/weams.rb
  spec/models/crosswalk_issue_spec.rb
Labels: BAH

#539 Remove quotation marks from SCO csv during upload
  app/controllers/uploads_controller.rb
  app/models/upload.rb
  config/csv_file_defaults.yml
  sample_csvs/program.csv
  spec/controllers/dashboards_controller_spec.rb
  spec/controllers/uploads_controller_spec.rb
  spec/fixtures/school_certifying_official.csv
Labels: BAH

#541 Accessibility fixes - input labels and heading tag updates
  app/views/crosswalks/index.html.erb
  app/views/dashboards/index.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/uploads/_csv_type_static.html.erb
  app/views/uploads/_form.html.erb
Labels: BAH

#540 fixed ANDI color contrast conflicts
  app/assets/stylesheets/application.css
  app/views/dashboards/_latest_upload.html.erb
  app/views/dashboards/_version.html.erb
  app/views/dashboards/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/storages/_introduction.html.erb
  app/views/storages/_storage.html.erb
  app/views/uploads/_introduction.html.erb
  sample_csvs/program.csv
Labels: BAH

#531 Ipeds Orphan Crosswalk Issues migration
  db/migrate/20191219210003_add_issue_type_column_to_crosswalk_issues.rb
  db/schema.rb
Labels: BAH

#530 Crosswalk Issues - Ipeds Orphans
  app/assets/stylesheets/application.css
  app/controllers/crosswalks_controller.rb
  app/models/crosswalk_issue.rb
  app/views/crosswalks/_orphan_issues.html.erb
  app/views/crosswalks/_partial_issues.html.erb
  app/views/crosswalks/orphans.html.erb
  app/views/crosswalks/partials.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/storages/index.html.erb
  config/routes.rb
  db/seeds/02_data.rb
  spec/controllers/crosswalks_controller_spec.rb
  spec/factories/crosswalk_issues.rb
  spec/factories/crosswalks.rb
  spec/models/crosswalk_issue_spec.rb
Labels: BAH

#536 Add lib/common/client code from vets-api (no REDIS) to use for API calls within GIDS
  .rubocop.yml
  config/locales/exceptions.en.yml
  lib/common/client/base.rb
  lib/common/client/configuration/base.rb
  lib/common/client/configuration/rest.rb
  lib/common/client/errors.rb
  lib/common/client/middleware/response/json_parser.rb
  lib/common/client/middleware/response/raise_error.rb
  lib/common/client/middleware/response/snakecase.rb
  lib/common/exceptions.rb
  lib/common/exceptions/exception_handler.rb
  lib/common/exceptions/external/backend_service_exception.rb
  lib/common/exceptions/external/gateway_timeout.rb
  spec/lib/common/client/base_spec.rb
  spec/lib/common/client/configuration/base_spec.rb
  spec/lib/common/exceptions/exception_handler_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/client_helper.rb
  spec/support/configuration_helper.rb
  spec/support/default_configuration_helper.rb
Labels: BAH, BAH-QA-needed

#542 Bah info box issues: extra bullet point, wrong value in the Column Separator drop-down on upload results in "Something Went Wrong" error message
  app/controllers/uploads_controller.rb
  app/views/dashboards/index.html.erb
  app/views/uploads/new.html.erb
Labels: BAH, BAH-QA-needed

#534 GIDS: Use Scorecard API to replace flat-file upload
  README.md
  app/assets/javascripts/upload.js
  app/controllers/dashboards_controller.rb
  app/controllers/uploads_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/scorecard.rb
  app/models/upload.rb
  app/utilities/scorecard_api/service.rb
  app/views/dashboards/_latest_upload.html.erb
  app/views/dashboards/index.html.erb
  config/application.rb
  config/initializers/csv_types.rb
  config/initializers/faraday_middleware.rb
  config/locales/exceptions.en.yml
  config/routes.rb
  config/settings.yml
  lib/common/client/base.rb
  lib/common/client/configuration/rest.rb
  lib/common/client/middleware/response/json_parser.rb
  lib/common/client/middleware/response/raise_error.rb
  lib/common/client/middleware/response/scorecard_api_errors.rb
  lib/common/client/middleware/response/snakecase.rb
  lib/common/exceptions.rb
  lib/common/exceptions/exception_handler.rb
  lib/common/exceptions/internal/service_outage.rb
  lib/csv_helper/loader.rb
  lib/scorecard_api/client.rb
  lib/scorecard_api/configuration.rb
  spec/config/initializers/csv_types_spec.rb
  spec/controllers/dashboards_controller_spec.rb
  spec/lib/common/client/configuration/base_spec.rb
  spec/lib/common/client/middleware/response/json_parser_spec.rb
  spec/lib/common/client/middleware/response/raise_error_spec.rb
  spec/lib/common/client/middleware/response/scorecard_api_errors_spec.rb
  spec/lib/common/client/middleware/response/snakecase_spec.rb
  spec/lib/common/exceptions/exception_handler_spec.rb
  spec/lib/scorecard_api/client_spec.rb
  spec/lib/scorecard_api/configuration_spec.rb
  spec/models/scorecard_spec.rb
  spec/models/upload_spec.rb
  spec/rails_helper.rb
  spec/support/fix_all.rb
  spec/utilities/scorecard_api/service_spec.rb
Labels: BAH

#544 update institution program to return caution flag data
  app/models/institution_program.rb
  app/serializers/institution_program_serializer.rb
  spec/serializers/institution_program_serializer_spec.rb
Labels: BAH

#546 GIDS: Use Scorecard API to replace flat-file upload
  README.md
  config/settings.yml
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#543 GIDS: Update dashboard after completed Scorecard API request: DB
  db/migrate/20200124135649_add_completion_date_to_uploads.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#547 GIDS: Update dashboard after completed Scorecard API request #4931
  app/assets/javascripts/upload.js
  app/controllers/dashboards_controller.rb
  app/controllers/uploads_controller.rb
  app/helpers/dashboards_helper.rb
  app/models/scorecard.rb
  app/models/upload.rb
  app/views/dashboards/_latest_upload.html.erb
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/uploads.rb
  spec/helpers/dashboards_helper_spec.rb
Labels: BAH, BAH-QA-needed

#552 Two users fetching scorecard data at the same time results in the data being duplicated #5208
  app/controllers/dashboards_controller.rb
  spec/controllers/dashboards_controller_spec.rb
Labels: BAH, BAH-QA-needed

#551 4038: Add Database specific changes
  db/migrate/20200107150000_add_institution_columns_to_school_certifying_officials.rb
  db/migrate/20200107150001_create_school_certifying_officials_archives.rb
  db/migrate/20200107150004_remove_institutions_version_constraint.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#554 User receives "Scorecard is already being fetched by another user" error when no other user is fetching #5312
  db/migrate/20200130135649_update_completion_date_in_uploads.rb
  db/schema.rb
Labels: BAH
