Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-07, with the labels that each got.

#677 Add "fuzzy search" of institutions by name and city
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH

#678 add physical zip and ialias criteria to free text institution search
  app/models/institution.rb
  app/models/ipeds_hd.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#679 Institution fuzzy search updates
  app/models/institution.rb
  spec/models/institution_spec.rb
Labels: BAH

#681 CT-Filter: Pull additional filter data via GIDS Scorecard Fetch API [DRAFT] #11086
  .gitignore
  app/utilities/scorecard_api/service.rb
Labels: BAH, BAH-QA-needed

#682 CF: Remove "VA may suspend benefits to this school." from caution flags #11116
  db/seeds/03_rules.rb
Labels: BAH, BAH-QA-needed

#680 Update Institution fuzzy-search order by
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH

#685 CT: Staging search functionality issues #11408
  app/models/institution.rb
  config/settings.yml
Labels: BAH, BAH-QA-needed

#688 CT: Issue when selecting an autocomplete suggestion #11436
  app/controllers/v0/institutions_controller.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH

#684 Bah addscorecardcolumns dbmigration
  db/migrate/20200717142410_add_scorecard_columns_to_institutions.rb
  db/migrate/20200717153030_add_scorecard_columns_to_institutions_archives.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#683 Bah addscorecard columns
  app/models/scorecard.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_serializer.rb
  spec/support/api/schemas/institution_profile.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#686 Bah 10985
  app/controllers/v0/institution_programs_controller.rb
  app/models/institution_program.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
Labels: BAH, BAH-QA-needed

#687 db changes for va caution flags
  app/models/va_caution_flag.rb
  db/migrate/20200718131012_create_va_caution_flags.rb
  db/schema.rb
  sample_csvs/va_caution_flag.csv
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#690 add institutions ialias column to exact match checks for institution search API
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#691 Change date columns to be strings in va_caution_flags table
  db/migrate/20200727113800_change_va_caution_flag_date_type.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#693 Change when fuzzy search with pgtrm is used
  .rubocop.yml
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-QA-needed
