Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-09, with the labels that each got.

#715 CT-Search: Exclude list of common words from fuzzy search functionality #13039
  app/models/institution.rb
  app/models/institution_program.rb
  app/serializers/institution_serializer.rb
  config/settings.yml
  spec/controllers/v0/institutions_controller_spec.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-QA-needed

#713 Add school_ratings table
  db/migrate/20200831132700_create_school_ratings.rb
  db/schema.rb
Labels: BAH

#717 Rails 5.2.4.4
  Gemfile.lock
Labels: BAH

#731 DB: GIBCT Search: University of Maryland institutions dont show in search results when searching "University of Maryland" #13408
  db/migrate/20200910194017_add_institution_search.rb
  db/migrate/20200911194017_add_institution_search_archive.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed

#730 GIBCT Search: University of Maryland institutions dont show in search results when searching "University of Maryland" #13408
  app/models/institution.rb
  app/models/weam.rb
  config/settings.yml
  spec/controllers/v0/institutions_controller_spec.rb
  spec/factories/institutions.rb
  spec/factories/weams.rb
  spec/models/shared_examples/shared_examples_for_exportable_by_version.rb
  spec/models/weam_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#732 Fix common word removal from processed institution search term
  app/models/institution.rb
  config/settings.yml
  spec/models/institution_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed
