Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2020-11, with the labels that each got.

#757 Specs: Add the ability to upload the accreditation excel file #13863
  app/controllers/groups_controller.rb
  app/controllers/uploads_controller.rb
  app/models/group.rb
  app/utilities/upload_types/upload_requirements.rb
  app/views/groups/_form.html.erb
  config/initializers/group_types.rb
  spec/controllers/groups_controller_spec.rb
  spec/controllers/shared_examples/shared_examples_for_authentication.rb
  spec/controllers/uploads_controller_spec.rb
  spec/factories/groups.rb
  spec/fixtures/accreditation.xlsx
  spec/utilities/upload_types/upload_requirements_spec.rb
Labels: BAH, BAH-IR-needed

#768 Force utf-8 encoding when uploading CSVs with Roo
  app/controllers/uploads_controller.rb
  lib/roo_helper/loader.rb
Labels: BAH, BAH-QA-needed

#766 Add rubyzip
  Gemfile
  Gemfile.lock
Labels: BAH

#767 15886: Remove SmartCSV Gem and usuage
  Gemfile
  Gemfile.lock
  app/models/importable_record.rb
  lib/common/exporter.rb
  lib/csv_helper/loader.rb
  lib/csv_helper/shared.rb
  lib/roo_helper/shared.rb
Labels: BAH, BAH-QA-needed

#769 GIDS: Seed Accreditation file type data#15765
  db/seeds/02_data.rb
  lib/seed_utils.rb
  sample_csvs/Accreditation.xlsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#764 GIDS: Add the ability to export the Accreditation file type #15630
  app/controllers/dashboards_controller.rb
  app/models/group.rb
  app/views/dashboards/_latest_upload.html.erb
  spec/controllers/dashboards_controller_spec.rb
  spec/models/group_spec.rb
Labels: BAH

#770 Remove requires of roo_helper in several files
  app/controllers/groups_controller.rb
  app/controllers/uploads_controller.rb
  app/models/importable_record.rb
  config/initializers/roo_helper.rb
Labels: BAH

#771 Update Makefile
  Makefile
  docker-compose.yml
Labels: BAH, BAH-QA-needed

#773 Update PULL_REQUEST_TEMPLATE.md
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: BAH

#772 CT Site Search - Selective Searching #15828
  app/models/institution.rb
  app/models/weam.rb
  spec/models/institution_spec.rb
Labels: BAH
