Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2021-06, with the labels that each got.

#827 CT Redesign: Institutions farther away than the designated distance limit are showing in search results
  app/models/institution.rb
  spec/controllers/v1/institutions_controller_spec.rb
Labels: BAH

#829 Institution table Database change
  db/migrate/20210607132032_add_schools_employers_to_institutions.rb
  db/migrate/20210607134144_add_schools_employers_to_institutions_archive.rb
  db/schema.rb
Labels: BAH

#828 Add filtering to institution location search
  app/controllers/v1/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/weam.rb
  app/serializers/institution_search_result_serializer.rb
  config/routes.rb
  spec/controllers/v1/institutions_controller_spec.rb
  spec/factories/institutions.rb
Labels: BAH

#830 25559: Add programs to search results.
  app/serializers/institution_search_result_serializer.rb
  spec/support/api/schemas/institution_search_results.json
Labels: BAH

#831 Exclude bad lat/long values from going into Institutions table
  app/models/institution_builder.rb
  app/utilities/institution_builder/ipeds_builder.rb
  app/utilities/institution_builder/scorecard_builder.rb
  spec/factories/ipeds_hds.rb
Labels: BAH

#835 GIDS: Database: Add ability to upload VRRAP providers file
  db/migrate/20210614192028_create_vrrap_providers.rb
  db/migrate/20210615152425_add_vrrap_to_institutions.rb
  db/schema.rb
Labels: BAH

#833 GIDS: Add ability to upload VRRAP providers file
  .rubocop.yml
  app/controllers/groups_controller.rb
  app/controllers/uploads_controller.rb
  app/models/converters/boolean_converter.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/models/upload.rb
  app/models/vrrap_provider.rb
  app/serializers/institution_compare_serializer.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_search_result_serializer.rb
  app/utilities/institution_builder/vrrap_builder.rb
  app/utilities/upload_types/upload_requirements.rb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  lib/roo_helper/loader.rb
  lib/seed_utils.rb
  sample_csvs/vrrap_provider.xlsx
  spec/controllers/dashboards_controller_spec.rb
  spec/factories/vrrap_providers.rb
  spec/fixtures/vrrap_provider.csv
  spec/fixtures/vrrap_provider.xlsx
  spec/fixtures/vrrap_provider_invalid.xlsx
  spec/fixtures/vrrap_provider_missing_column.xlsx
  spec/models/shared_examples/shared_examples_for_exportable.rb
  spec/models/shared_examples/shared_examples_for_loadable.rb
  spec/models/vrrap_provider_spec.rb
  spec/support/api/schemas/institution_compare_results.json
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#832 25818: Add ability to upload section 1005 file (Database Setup)
  db/migrate/20210615173005_create_in_state_tuition_policy_url.rb
  db/migrate/20210615232604_add_in_state_tuition_information_to_institutions.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#834 25818: Add ability to upload section 1005 file
  app/models/in_state_tuition_policy_url.rb
  app/models/institution.rb
  app/models/institution_builder.rb
  app/serializers/institution_profile_serializer.rb
  app/utilities/institution_builder/in_state_tuition_policy_url_builder.rb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  sample_csvs/in_state_tuition_policy_url.csv
  spec/factories/in_state_tuition_policy_url.rb
  spec/fixtures/in_state_tuition_policy_url.csv
  spec/fixtures/in_state_tuition_policy_url_invalid.csv
  spec/models/in_state_tuition_policy_url_spec.rb
  spec/support/api/schemas/institution_compare_results.json
  spec/support/api/schemas/institution_profile.json
Labels: BAH

#836 added program length to compare serializer
  app/serializers/institution_compare_serializer.rb
  spec/support/api/schemas/institution_compare_results.json
Labels: BAH-IR-needed, BAH-QA-needed

#837 Export addresses with missing latitude or longitude for batch processing
  app/assets/stylesheets/application.css
  app/controllers/latitude_longitude_issues_controller.rb
  app/models/census_lat_long.rb
  app/models/group.rb
  app/models/institution.rb
  app/models/version.rb
  app/models/weam.rb
  app/views/dashboards/_latitude_longitude_issues.html.erb
  app/views/dashboards/index.html.erb
  config/routes.rb
  lib/common/exporter.rb
  spec/controllers/latitude_longitude_issues_controller_spec.rb
  spec/factories/institutions.rb
  spec/factories/weams.rb
  spec/models/census_lat_long_spec.rb
  spec/models/group_spec.rb
Labels: BAH
