Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2021-02, with the labels that each got.

#786 Update README.md to use db:setup
  README.md
Labels: BAH

#783 CT: Add IPEDS to Caution Flag Mappings #18306
  app/models/institution_builder.rb
  spec/models/institution_builder_spec.rb
Labels: BAH, BAH-QA-needed

#785 CT: Add country name to free text search #19516
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_program.rb
  spec/controllers/v0/institutions_controller_spec.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-QA-needed

#789 Rails 5.2.4.5
  Gemfile
  Gemfile.lock
Labels: BAH

#788 DB migration for cip code csv upload
  db/migrate/20210210111423_create_cip_code.rb
  db/schema.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#787 Added CIPCode Csv upload
  app/models/cip_code.rb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  sample_csvs/cip_code.csv
  spec/factories/cip_code.rb
  spec/fixtures/cip_code.csv
  spec/fixtures/cip_code_invalid.csv
  spec/fixtures/cip_code_missing_column.csv
  spec/models/cip_code_spec.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#792 Upgraded rails from 5.2.4.5 to 6.0.3.5
  Gemfile
  Gemfile.lock
  spec/models/institution_builder_spec.rb
Labels: BAH

#790 19571: Create scorecard degree program (DB Specific PR)
  db/migrate/2021021220441_create_scorecard_degree_program.rb
  db/schema.rb
Labels: BAH

#791 Bah 19571
  app/models/scorecard.rb
  app/models/scorecard_degree_program.rb
  app/utilities/scorecard_api/service.rb
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  sample_csvs/scorecard_degree_program.csv
  spec/factories/scorecards_degree_program.rb
  spec/fixtures/scorecard_degree_program.csv
  spec/fixtures/scorecard_degree_program_invalid.csv
  spec/fixtures/scorecard_degree_program_missing_column.csv
  spec/models/scorecard_degree_programs_spec.rb
  spec/utilities/scorecard_api/service_spec.rb
Labels: BAH, BAH-QA-needed
