Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2021-07, with the labels that each got.

#839 24332: At census_lat_longs table
  db/migrate/20210701165043_create_census_lat_longs.rb
  db/schema.rb
Labels: BAH, BAH-QA-needed

#841 Improve Sandbox search by name
  app/controllers/v1/institutions_controller.rb
  app/models/institution.rb
  app/serializers/institution_compare_serializer.rb
  app/serializers/institution_profile_serializer.rb
  app/serializers/institution_search_result_serializer.rb
  db/migrate/20210707151300_add_search_indexes_to_institution.rb
  db/schema.rb
Labels: BAH

#840 24332: Import census tool latitude or longitude data
  app/controllers/latitude_longitude_issues_controller.rb
  app/models/census_lat_long.rb
  app/models/upload.rb
  app/views/dashboards/_latitude_longitude_issues.html.erb
  app/views/latitude_longitude_issues/_form.html.erb
  app/views/latitude_longitude_issues/_introduction.html.erb
  app/views/latitude_longitude_issues/_upload_messages.html.erb
  app/views/latitude_longitude_issues/new.html.erb
  app/views/latitude_longitude_issues/show.html.erb
  config/csv_file_defaults.yml
  config/routes.rb
  lib/common/shared.rb
  lib/roo_helper/loader.rb
  sample_csvs/census_lat_long.csv
  spec/controllers/latitude_longitude_issues_controller_spec.rb
  spec/factories/census_lat_longs.rb
  spec/factories/uploads.rb
  spec/fixtures/census_lat_long.csv
  spec/fixtures/census_lat_long_caret.csv
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#845 Add weams in_state_tuition_information (1 of 3)
  db/migrate/20210716084900_add_in_state_tuition_information_to_weams.rb
  db/schema.rb
Labels: BAH

#844 Add weams in_state_tuition_information (2 of 3)
  app/models/in_state_tuition_policy_url.rb
  app/models/institution_builder.rb
  app/models/weam.rb
  app/utilities/institution_builder/in_state_tuition_policy_url_builder.rb
  config/csv_file_defaults.yml
  config/initializers/csv_types.rb
  db/seeds/02_data.rb
  spec/factories/in_state_tuition_policy_url.rb
  spec/models/in_state_tuition_policy_url_spec.rb
Labels: BAH

#838 CT Redesign: Populate missing latitude and longitude values
  app/controllers/dashboards_controller.rb
  app/models/institution_builder.rb
  app/utilities/institution_builder/lat_long_builder.rb
  app/utilities/institution_builder/scorecard_builder.rb
  spec/factories/institutions.rb
  spec/models/institution_builder_spec.rb
Labels: BAH
