Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2021-01, with the labels that each got.

#780 update nokogiri for security warning
  Gemfile.lock
Labels: BAH, BAH-IR-needed

#779 18313: Gemfile specific update
  Gemfile
  Gemfile.lock
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#778 18313: CT: Add ability to search using state abbreviation
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH

#781 Move vets-json-schema to correct group
  Gemfile
Labels: BAH, BAH-IR-needed
