Repository department-of-veterans-affairs/gibct-data-service, pull requests merged in 2021-03, with the labels that each got.

#798 Remove Activerecord session store
  Gemfile
  Gemfile.lock
  config/initializers/session_store.rb
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#797 GIBCT Inaccessible in local builds
  config/environments/development.rb
  config/settings.yml
Labels: BAH, BAH-IR-needed

#796 CT: searching for an institution with a single quote in name is not returning results #21123
  app/models/institution.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-QA-needed

#799 CT: searching for an institution with a colon in name is not returning results #21401
  app/models/institution.rb
  spec/models/institution_spec.rb
Labels: BAH, BAH-QA-needed

#800 Removed support for gibctStateSearch feature flag
  app/controllers/v0/institution_programs_controller.rb
  app/controllers/v0/institutions_controller.rb
  app/models/institution.rb
  app/models/institution_program.rb
  spec/controllers/v0/institution_programs_controller_spec.rb
  spec/controllers/v0/institutions_controller_spec.rb
Labels: BAH

#801 update mimemagic
  Gemfile.lock
Labels: BAH

#802 Mimemagic 0.3.7
  Dockerfile
  Gemfile
  Gemfile.lock
  config/initializers/session_store.rb
Labels: BAH
